# Generated by Django 5.1.1 on 2024-09-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.TextField()),
                ('Topic', models.TextField()),
                ('Sub_Topic', models.TextField()),
                ('Question', models.TextField()),
                ('Options', models.TextField()),
                ('Answer', models.TextField()),
            ],
        ),
    ]
