# Generated by Django 5.1.1 on 2024-10-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Level', models.CharField(max_length=50)),
                ('Topic', models.CharField(max_length=100)),
                ('Sub_Topic', models.CharField(max_length=100)),
                ('Question', models.TextField()),
                ('Options', models.TextField(max_length=255)),
                ('OptionA', models.CharField(max_length=255)),
                ('OptionB', models.CharField(max_length=255)),
                ('OptionC', models.CharField(max_length=255)),
                ('OptionD', models.CharField(max_length=255)),
                ('Answer_Option', models.CharField(max_length=255)),
                ('Answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Sample1',
        ),
    ]
